name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      kernel_type:
        description: 'Kernel Type PerfKernel or AlfaKernel'
        required: true
        default: 'AlfaKernel'
        type: string
      is_release:
        description: 'Kernel Release at github true or false'
        required: true
        default: false
        type: boolean

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      KERNEL_NAME: "courbet"
      KERNEL_DIR: "kernel_xiaomi"
      ARCH: "arm64"
      SUBARCH: "arm64"
      KBUILD_BUILD_USER: "ask9027"
      KBUILD_BUILD_HOST: "github"
      KERNEL_TYPE: "${{ inputs.kernel_type }}"
      IS_RELEASE: "${{ inputs.is_release }}"

    steps:
    - name: update and download required packages
      run: sudo apt update && sudo apt install -y git bc bison flex libssl-dev make automake build-essential curl zip clang lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libdebuginfod1 elfutils
#
#    - name: setup neutron clang
#      run: |
#        mkdir -p "${GITHUB_WORKSPACE}/toolchains/neutron-clang"
#        cd "${GITHUB_WORKSPACE}/toolchains/neutron-clang"
#        curl -LO "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman"
#        chmod +x antman
#        ./antman -S=05012024
#        ./antman --patch=glibc
#        cd ${GITHUB_WORKSPACE}
#
    - name: clone kernel source
      run: |
        cd ${GITHUB_WORKSPACE}
        if [ "${KERNEL_TYPE}" == "AlfaKernel" ]; then
          git clone --recurse-submodules https://github.com/ask9027/kernel_xiaomi_sm6150.git -b quattordici-miui ${KERNEL_DIR}
        else
          git clone https://github.com/omer12544/kernel_xiaomi_courbet.git -b perf-ksu-miui ${KERNEL_DIR}
        fi

    - name: build kernel from source
      run: |
        cd ${GITHUB_WORKSPACE}/${KERNEL_DIR}
        export ARCH=${ARCH}
        make O=out ${KERNEL_NAME}_defconfig
        make -j$(nproc --all) \
        O=out CC=clang \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        CONFIG_NO_ERROR_ON_MISMATCH=y

        KERNEL_VERSION=$(make kernelversion)
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV

        mkdir ${GITHUB_WORKSPACE}/output
        cp out/arch/arm64/boot/Image.gz ${GITHUB_WORKSPACE}/output/
        cp out/arch/arm64/boot/dtb.img ${GITHUB_WORKSPACE}/output/
        cp out/arch/arm64/boot/dtbo.img ${GITHUB_WORKSPACE}/output/
        cd ${GITHUB_WORKSPACE}

    - name: create anykernel3 zip
      run: |
        git clone https://github.com/ask9027/AnyKernel3.git -b ${KERNEL_TYPE,,}
        cp output/* AnyKernel3/
        cd AnyKernel3
        buildTime=$(date '+%Y%m%d-%H%M%S')
        zip -r9 ../${KERNEL_TYPE}-miui-${KERNEL_VERSION}-${KERNEL_NAME}-${buildTime}.zip * -x .git README.md *placeholder
        cd ${GITHUB_WORKSPACE}

    - name: upload kernel output
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_TYPE }}-miui-${{ env.KERNEL_VERSION }}-${{ env.KERNEL_NAME }}
        path: ${{ env.KERNEL_TYPE }}-miui*.zip

    - name: Create release
      if: ${{ env.IS_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ env.KERNEL_VERSION }}
        name: "Kernel Version ${{ env.KERNEL_VERSION }}"
        body: '${{ env.KERNEL_VERSION }}-${{ env.KERNEL_NAME }} for Stock MIUI-ROM'
        draft: false
        prerelease: false
        generate_release_notes: false
        files: ${{ env.KERNEL_TYPE }}-miui*.zip
